### ISSUE TITLE
Duplicate code for player 1 frameScore setting duplicate code

### ISSUE THREAD

**Issue by RahulNagekar** [adriantache/Bowling-Scoring#14]
TextView frames for player 1 are mapped to the respective variables. This can be handled using arrays instead of creating multiple variables. Also, duplicate code to set these can be removed with this approach.

**Comment by adriantache** [comment]
I appreciate your suggestion, and I understand your approach, but I feel it complicates code and decreases readability with the very small benefit of reducing code size (it's machine generated so there's no problem editing it).  It's certainly a nice idea, but for me not one worth refactoring the entire codebase for.

For the sake of conversation, I feel using a different kind of view would have made more sense, some custom view that just takes the array and displays it as a table, but I've kind of moved on from actively developing this app.
