### ISSUE TITLE
No undo button

### ISSUE THREAD

**Issue by adriantache** [adriantache/Bowling-Scoring#3]

**Comment by colemclark1** [comment]
I'm new to Github but would like to try to add an undo button for you

**Comment by adriantache** [comment]
Sure, have at it :) If you manage to get it done, please submit a pull request containing only the modified files. Furthermore, please only modify features that are directly related to this functionality and completely necessary. Thanks!

**Comment by colemclark1** [comment]
Thanks! I added a pull request for the undo button. It took quite a bit of logic but I believe I got everything to work correctly including the 10th frame and how to process strikes.

**Comment by adriantache** [comment]
Interesting, I'll have a look and if everything seems okay I'll merge it some time tomorrow, hopefully. Thanks for your contribution :)

**Comment by colemclark1** [comment]
No problem! I thought the app looked great! Good Work!

**Comment by adriantache** [comment]
Ah, I've discovered an interesting bug with this! If you undo at the beginning of a frame, the predictor of remaining pins (`maxPins`) is confused, and remembers the last number you chose instead of resetting to 10. I made this happen by going to frame two, inputting a number, then hitting undo, and the number it suggested was not strike. Hitting undo and coming back, the number becomes the difference between that number and 10. If you feel like it, please merge master into your branch and try to fix it :)

**Comment by colemclark1** [comment]
Ah I thought I got them all! haha Ok, I just want to make sure I understand the bug correctly. So you are saying, if I'm player 1 and I'm on the 2nd frame and I roll my first ball and then I input a score of lets say 3. The suggested pins changes to 7, since 7+3=10. Then before rolling my 2nd ball of the frame, I click the undo button and the suggested pins **should** change to a strike ("X") instead of staying at 7. Is that correct?

**Comment by colemclark1** [comment]
I'm new to Git and I'm trying to navigate how to merge the master branch with my local fork. I merged a new pull request and I think it worked, but if I did something wrong please let me know so I can change it back if needed

**Comment by adriantache** [comment]
Your understanding of the bug is correct :) 

It's very simple, I think. You can just fetch my branch by doing `git fetch upstream` and then `git merge upstream/master master` (if you're working on your master branch). 

https://help.github.com/articles/syncing-a-fork/

Alternatively, you could probably just fork the project again, I think.
